// build-config.js — reads .env and generates config.js for the browser.
// Run with:  node build-config.js
//
// The values are XOR-scrambled + base64'd with a random salt on every build so
// they aren't readable in config.js. NOTE: this is obfuscation, not security —
// the browser must decode the values to use them, so they are still visible in
// DevTools (Network tab / window.ENV). Protect your data with Row Level Security.
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const envPath = path.join(__dirname, '.env');
if (!fs.existsSync(envPath)) {
    console.error('Missing .env file next to build-config.js');
    process.exit(1);
}

const env = {};
fs.readFileSync(envPath, 'utf8').split(/\r?\n/).forEach(line => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return;
    const i = trimmed.indexOf('=');
    if (i === -1) return;
    env[trimmed.slice(0, i).trim()] = trimmed.slice(i + 1).trim().replace(/^["']|["']$/g, '');
});

for (const key of ['SUPABASE_URL', 'SUPABASE_ANON_KEY']) {
    if (!env[key]) { console.error('Missing ' + key + ' in .env'); process.exit(1); }
}

const salt = crypto.randomBytes(12).toString('hex');

function scramble(str) {
    const bytes = Buffer.from(str, 'utf8');
    const out = Buffer.alloc(bytes.length);
    for (let i = 0; i < bytes.length; i++) out[i] = bytes[i] ^ salt.charCodeAt(i % salt.length);
    return out.toString('base64');
}

const out = `// AUTO-GENERATED by build-config.js from .env — do not edit by hand.
(function () {
    var s = ${JSON.stringify(salt)};
    function d(b64) {
        var b = atob(b64), o = '';
        for (var i = 0; i < b.length; i++) o += String.fromCharCode(b.charCodeAt(i) ^ s.charCodeAt(i % s.length));
        return o;
    }
    window.ENV = {
        SUPABASE_URL: d(${JSON.stringify(scramble(env.SUPABASE_URL))}),
        SUPABASE_ANON_KEY: d(${JSON.stringify(scramble(env.SUPABASE_ANON_KEY))})
    };
})();
`;
fs.writeFileSync(path.join(__dirname, 'config.js'), out);
console.log('config.js generated (scrambled).');
