// AUTO-GENERATED by build-config.js from .env — do not edit by hand.
(function () {
    var s = "34d0fe19353235755eafae97";
    function d(b64) {
        var b = atob(b64), o = '';
        for (var i = 0; i < b.length; i++) o += String.fromCharCode(b.charCodeAt(i) ^ s.charCodeAt(i % s.length));
        return o;
    }
    window.ENV = {
        SUPABASE_URL: d("W0AQQBVfHhZDT15UQFdWX1gLFREXE09PV1gWUUgWRElSV1JBVhtUWg=="),
        SUPABASE_ANON_KEY: d("Vk0uWAQiUlB8XHl7Zk9+BHsMKBUoC2sCUHctBi8OQWFldnkLHVBOf0UGUisIKlB9SVA8cg48XH9Jb2B7QHxZf1k/CC9XLFd1BVYzahw8XH9CV2QHA1EEbwcBDw4KB3F9W30NRw8GXABAb2B7BXxac0AHU1IIKXp9Q208YQ8qW3wAe0lrAntjYEwqNSMSLFRhB1cneVAoW3gGeFl3SXhjfAAoOVZPM2pvAgQBeSRSUFtYdFRYWwR1UwYyJSAHKlQPRVkpdRc2AHVlcVhHXEVtcA==")
    };
})();
